cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add, name='product_add'),
    path('remove/<product_id>/', remove, name='product_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('coupon/', include('coupon.urls')),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
]

coupon/urls.py
from django.urls import path
from .views import add_coupon

app_name = 'coupon'

urlpatterns = [
    path('add/', add_coupon, name='add')
]

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

coupon/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class Coupon(models.Model):
    code = models.CharField(max_length=50, unique=True)
    use_from_date = models.DateTimeField()
    use_to_date = models.DateTimeField()
    amount = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(100000)])
    active = models.BooleanField()

    def __str__(self):
        return self.code

shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    meta_description = models.TextField(blank=True)

    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_in_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)

    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    meta_description = models.TextField(blank=True)

    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()

    available_display = models.BooleanField('Display', default=True)
    available_order = models.BooleanField('Order', default=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']
        index_together = [['id', 'slug']]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms

class AddProductForm(forms.Form):
    quantity = forms.IntegerField()
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

coupon/forms.py
from django import forms

class AddCouponForm(forms.Form):
    code = forms.CharField(label='Your Coupon Code')

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .forms import AddProductForm
from .cart import Cart
from coupon.forms import AddCouponForm


# Create your views here.
@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = AddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], is_update=cd['is_update'])

    return redirect('cart:detail')


def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')


def detail(request):
    cart = Cart(request)
    add_coupon = AddCouponForm()
    for product in cart:
        product['quantity_form'] = AddProductForm(initial={'quantity': product['quantity'], 'is_update': True})
    return render(request, 'cart/detail.html', {'cart': cart, 'add_coupon':add_coupon})

coupon/views.py
from django.shortcuts import redirect
from django.utils import timezone
from django.views.decorators.http import require_POST
from .models import Coupon
from .forms import AddCouponForm


# Create your views here.
@require_POST
def add_coupon(request):
    now = timezone.now()
    form = AddCouponForm(request.POST)
    if form.is_valid():
        code = form.cleaned_data['code']
        try:
            coupon = Coupon.objects.get(code__iexact=code, use_from_date__lte=now, use_to_date__gte=now, active=True)
            request.session['coupon_id'] = coupon.id
        except Coupon.DoesNotExist:
            request.session['coupon_id'] = None
    return redirect('cart:detail')

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from cart.forms import AddProductForm

# Create your views here.

def product_in_category(request, category_slug=None):
    current_category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available_display=True)

    if category_slug:
        current_category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=current_category)

    return render(request, 'shop/list.html', {'current_category': current_category, 'categories': categories, 'products': products})

def product_detail(request, id, product_slug=None):
    product = get_object_or_404(Product, id=id, slug=product_slug)
    add_to_cart = AddProductForm(initial={'quantity':1})
    return render(request, 'shop/detail.html', {'product':product, 'add_to_cart':add_to_cart})

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Shopping cart
{% endblock %}

{% block content %}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Image</th>
            <th scope="col">Product</th>
            <th scope="col">Quantity</th>
            <th scope="col">Remove</th>
            <th scope="col">Unit price</th>
            <th scope="col">Price</th>
        </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr>
        <th scope="row">
            <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image.url }}" class="img-thumbnail">
            </a>
        </th>
        <td>{{ product.name }}</td>
        <td>
            <form action="{% url 'cart:product_add' product.id %}" method="post">
                {{ item.quantity_form.quantity }}
                {{ item.quantity_form.is_update }}
                <input type="submit" class="btn btn-primaty" value="Update">
                {% csrf_token %}
            </form>
        </td>
        <td><a href="{% url 'cart:product_remove' product.id %}">Remove</a> </td>
        <td class="num">${{ item.price }}</td>
        <td class="num">${{ item.total_price }}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    {% if cart.coupon %}
    <tr class="subtotal">
        <td>Subtotal</td>
        <td colspan="4"></td>
        <td>${{ cart.get_product_total }}</td>
    </tr>
    <tr>
        <td>"{{ cart.coupon.code }}" coupon (${{ cart.coupon.amount }})</td>
        <td colspan="4"></td>
        <td>- ${{ cart.get_discount_total|floatformat:"2" }}</td>
    </tr>
    {% endif %}
    <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price|floatformat:"2" }}</td>
    </tr>
    </tbody>
</table>
<p>
    Add Coupon:
</p>
<form action="{% url 'coupon:add' %}" method="post">
    {{ add_coupon }}
    <input type="submit" value="Add">
    {% csrf_token %}
</form>

<p class="text-right">
    <a href="{% url 'shop:product_all' %}" class="btn btn-primary">Continue shopping</a>
</p>
{% endblock %}

shop/templates/shop/detail.html
{% extends 'base.html' %}

{% block title %}Product Detail{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4">
            <img src="{{product.image.url}}" width="100%">
        </div>
        <div class="col">
            <h1 class="display-6">{{product.name}}</h1>
            <p><span class="badge badge-secondary">Price</span>{{product.price}}</p>
            <form action="{% url 'cart:product_add' product.id %}" method="post">
                {{add_to_cart}}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary btn-sm" value="Add to cart">
            </form>
            <h5><span class="badge badge-secondory">Description</span>{{product.description|linebreaks}}</h5>
        </div>
    </div>
</div>

{% endblock %}

shop/templates/shop/list.html
{% extends 'base.html' %}
{% block title %}Category Page{% endblock %}
{% block content %}

<div class="row">
    <div class="col-2">
        <div class="list-group">
            <a href="/" class="list-group-item {% if not current_category %}active{% endif %}">All</a>
            {% for c in categories %}
            <a href="{{c.get_absolute_url}}" class="list-group-item {% if current_category.slug == c.slug %}active{% endif %}">{{c.name}}</a>
            {% endfor %}
        </div>
    </div>

    <div class="col">
        <div class="alert alert-info" role="alert">
            {% if current_category %}{{ current_category.name}}{% else %}All Products{% endif %}
        </div>
        <div class="row">
            {% for product in products %}
            <div class="col-4">
                <div class="card">
                    <img class="card-img-top" src="{{product.image.url}}" alt="Product Image">
                    <div class="card-body">
                        <h5 class="card-title">{{product.name}}</h5>
                        <p class="card-text">{{product.description}} <span class="badge badge-secondary">${{product.price}}</span></p>
                        <a href="{{product.get_absolute_url}}" class="btn btn-primary">View Detail</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- jquery slim 지우고 minified 추가 -->
    <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>


    {% block script %}
    {% endblock %}

    {% block style %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Django Shop</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav justify-content-end">
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                {% else %}
                <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                {% endif %}
            </li>
            <li class="nav-item">
                <a class="nav-link btn btn-outline-success" href="{% url 'cart:detail' %}">Cart
                    {% if cart|length > 0 %}
                        ${{ cart.get_total_price }} with {{cart|length}} items
                    {% else %}
                        : Empty
                    {% endif %}
                </a>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>